CREATE TABLE [User] (
	[Id]		BIGINT			NOT NULL	CONSTRAINT PK_Users_Id PRIMARY KEY IDENTITY
   ,[UserName]	NVARCHAR(100)	NOT NULL
   ,[Email]		NVARCHAR(100)	NOT NULL 
   ,[Password]  NVARCHAR(100)	NOT NULL
)
GO 

CREATE TABLE [InstaAccount] (
	[Id]	BIGINT	NOT NULL	CONSTRAINT PK_InstaAccount PRIMARY KEY IDENTITY
   ,[AccountLink] VARCHAR(200)	NULL,

)